template_path: remote-templates/AccountAlertTopics.yaml
stack_name: AccountAlertTopics
dependencies:
  - bootstrap
parameters:
  InitialSubscriberEmail: "sage-it@sagebase.org"
  EnableSubscriberSMS: "false"
  BillingThreshold: "2000"
  DeployLambda: "true"
  SlackWebhookURL: !ssm /infra/SlackWebhookUrl
  SlackChannel: "#infra-notices"
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/AccountAlertTopics.yaml --create-dirs -o remote-templates/AccountAlertTopics.yaml"
