template_path: remote/peer-route-config.yaml
stack_name: peer-defaultvpc-admincentral
dependencies:
  - prod/defaultvpc.yaml
parameters:
  PeeringConnectionId: pcx-94db07fc
  VpcPrivateRouteTable: rtb-3df21042
  VpcPublicRouteTable: rtb-2eec0e51
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/peer-route-config.yaml --create-dirs -o templates/remote/peer-route-config.yaml"
