template_path: remote-templates/peer-route-config.yaml
stack_name: peer-defaultvpc-admincentral
dependencies:
  - defaultvpc
parameters:
  PeeringConnectionId: pcx-94db07fc
  VpcPrivateRouteTable: rtb-3df21042
  VpcPublicRouteTable: rtb-2eec0e51
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/peer-route-config.yaml --create-dirs -o remote-templates/peer-route-config.yaml"
